name: main

on:
  push:
    branches:
      - 'main'

env:
  TEST_TAG: hexletcomponents/devops-example-app:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - run: docker run --rm ${{ env.TEST_TAG }} npm test

      - name: Build and push app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hexletcomponents/devops-example-app:latest
